#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE ${SPHERE_DB_ROLE}
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
  CREATE USER ${SPHERE_DB_USER} LOGIN
    ENCRYPTED PASSWORD '${SPHERE_DB_PASSWORD}';
  GRANT ${SPHERE_DB_ROLE} TO ${SPHERE_DB_USER};
  CREATE DATABASE ${SPHERE_DB_ROLE}
    WITH OWNER = ${SPHERE_DB_ROLE}
         ENCODING = 'UTF8'
         TABLESPACE = pg_default
         LC_COLLATE = 'en_US.utf8'
         LC_CTYPE = 'en_US.utf8'
         CONNECTION LIMIT = -1;
  \\connect ${SPHERE_DB_ROLE};
  CREATE SCHEMA ${SPHERE_DB_USER}
    AUTHORIZATION ${SPHERE_DB_USER};
EOSQL
